### ISSUE TITLE
Server cannot set status after HTTP headers have been sent

### ISSUE THREAD

**Issue by JurrianK** [Geta/404handler#134]
We seem to be getting the following exception at certain times: `Server cannot set status after HTTP headers have been sent`. We are still investigating what causes this exception to trigger, but we're hoping you could help us solve this issue.

**Error message:**
`Error on 404 handling. System.Web.HttpException (0x80004005): Server cannot set status after HTTP headers have been sent. at System.Web.HttpResponse.set_StatusCode(Int32 value) at BVNetwork.NotFound.Core.Web.HttpContextBaseExtensions.SetStatusCode(HttpContextBase context, Int32 statusCode) at BVNetwork.NotFound.Core.ErrorHandler.Handle(HttpContextBase context) at BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization.OnError(Object sender, EventArgs eventArgs)`

**Full stacktrace**
`System.Web.HttpException (0x80004005): Server cannot set status after HTTP headers have been sent.
   at System.Web.HttpResponse.set_StatusCode(Int32 value)
   at BVNetwork.NotFound.Core.Web.HttpContextBaseExtensions.SetStatusCode(HttpContextBase context, Int32 statusCode)
   at BVNetwork.NotFound.Core.ErrorHandler.Handle(HttpContextBase context)
   at BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization.OnError(Object sender, EventArgs eventArgs)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at System.Web.HttpApplication.RaiseOnError()`

Thanks in advance!

**Comment by marisks** [comment]
Which version of the library do you use?

**Comment by JurrianK** [comment]
The version in question is 11.1.12

**Comment by marisks** [comment]
The latest version logs this error as a warning. It was not possible to fix it so that it doesn't throw an exception at all.
