### ISSUE TITLE
We are getting these errors in our Epi logs. BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization : Error on 404 handling. 

### ISSUE THREAD

**Issue by christinekirsten** [Geta/404handler#143]
We are getting the following errors in our logs. Any ideas on how to fix or what could be the issue?

Thanks!

BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization : Error on 404 handling.
EPiServer.ServiceLocation.ActivationException: Activation error occurred while trying to get instance of type RequestHandler, key """" ---> StructureMap.Building.StructureMapBuildException: Failure while building 'Lambda: Invoke(value(EPiServer.ServiceLocation.Internal.Struc
tureMapConfiguredType`1+<>c__DisplayClass11_0`1[BVNetwork.NotFound.Core.CustomRedirects.IRedirectHandler,BVNetwork.NotFound.Core.CustomRedirects.IRedirectHandler]).instanceAccessor, value(EPiServer.ServiceLocation.Internal.StructureMapConfiguredType`1[BVNetwork.NotFound.Core
.CustomRedirects.IRedirectHandler])._serviceLocator)', check the inner exception for details
1.) Lambda: Invoke(value(EPiServer.ServiceLocation.Internal.StructureMapConfiguredType`1+<>c__DisplayClass11_0`1[BVNetwork.NotFound.Core.CustomRedirects.IRedirectHandler,BVNetwork.NotFound.Core.CustomRedirects.IRedirectHandler]).instanceAccessor, value(EPiServer.ServiceLocat
ion.Internal.StructureMapConfiguredType`1[BVNetwork.NotFound.Core.CustomRedirects.IRedirectHandler])._serviceLocator)
2.) Instance of BVNetwork.NotFound.Core.CustomRedirects.IRedirectHandler
3.) new RequestHandler(*Default of IRedirectHandler*, *Default of IRequestLogger*, *Default of IConfiguration*)
4.) BVNetwork.NotFound.Core.RequestHandler
5.) Instance of BVNetwork.NotFound.Core.RequestHandler
6.) Container.GetInstance(BVNetwork.NotFound.Core.RequestHandler)
 ---> System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Monitor.Enter(Object obj)
   at BVNetwork.NotFound.Core.CustomRedirects.CustomRedirectHandler.get_Current()
   at EPiServer.ServiceLocation.Internal.StructureMapConfiguration.TypedFactory`1.<Create>b__2_0(IServiceLocator s)
   at lambda_method(Closure , IBuildSession , IContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , IBuildSession , IContext )
   at StructureMap.Building.BuildPlan.Build(IBuildSession session, IContext context)
   at StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle)
   at StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph)
   at StructureMap.Container.GetInstance(Type pluginType)
   at EPiServer.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key)
   --- End of inner exception stack trace ---
   at EPiServer.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key)
   at EPiServer.ServiceLocation.ServiceLocatorImplBase.GetInstance[TService]()
   at EPiServer.ServiceLocation.Injected`1.get_Service()
   at BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization.OnEndRequest(Object sender, EventArgs eventArgs

**Comment by marisks** [comment]
Is this still an issue? It looks like you have some misconfiguration of EPiserver.
