### ISSUE TITLE
404 Page causes 500 since update from 11.2.1

### ISSUE THREAD

**Issue by AlexB-Adv** [Geta/404handler#150]
We were running on 11.1.12 and you could navigate to a non-existent page or directly to the 404 page's url and you would see our 404 page.
Then we updated to 11.2.3 and we could do neither of those things. We've worked backward in versions and we are running as expected on v11.2.1

My logs aren't helping too much:
`2019-04-08 14:59:45,517 [84] ERROR EPiServer.Global: Unhandled exception in ASP.NET
System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at BVNetwork.NotFound.Core.NotFoundPage.NotFoundPageUtil.SetCurrentLanguage(HttpContextBase context)
   at BVNetwork.NotFound.Core.NotFoundPage.NotFoundPageAttribute.OnActionExecuting(ActionExecutingContext filterContext)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__31(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeActionMethodWithFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor, IDictionary`2 parameters, AsyncCallback callback, Object state)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.BeginInvokeAction(ControllerContext controllerContext, String actionName, AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.<BeginExecuteCore>b__1c(AsyncCallback asyncCallback, Object asyncState, ExecuteCoreState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecuteCore(AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.<BeginExecute>b__14(AsyncCallback asyncCallback, Object callbackState, Controller controller)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Controller.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.BeginExecute(RequestContext requestContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__4(AsyncCallback asyncCallback, Object asyncState, ProcessRequestState innerState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncVoid`1.CallBeginDelegate(AsyncCallback callback, Object callbackState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state)
   at System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)`

We are a single language site FWIW.
The relevant sections in our web.config haven't changed, below being the main entry:
`<httpErrors errorMode="Custom" existingResponse="Replace">
      <remove statusCode="404" />
      
      <error statusCode="404" path="/404/" responseMode="ExecuteURL" />
    </httpErrors>`

Anyone able to help? Happy to provide more info if needed.

**Comment by kmukku** [comment]
I had this same error. On our case it happens only when browsing directly to 404 page ie. /en/404/.

**Comment by songfogeln** [comment]
Any updates on this? I'm having the same problem - receiving an error when browsing directly to the error page.

**Comment by marisks** [comment]
@songfogeln Have you tried the latest version?

**Comment by songfogeln** [comment]
yes @marisks , I receive the error when using the 11.3.0 version

**Comment by alexanddercrb** [comment]
Any news with this? I tried to replicate the attribute in order to be able to debug and everything is working as expected now. Whenever i try to switch back to 404Handler attribute, I have the error.

**Comment by alexanddercrb** [comment]
Hello guys. I have replicated my code for my situation and i found out that GetUrlNotFoundFromQueryString method is returning an empty string. Why? Because the IsValidQueryString method says so. It checks if the prefix of the query is 404, 410, or aspxerrorpath=.
In my case the query looks like this: "route=/some-folder/folder/page-name/".
So, in my case the urlNotFound variable inside SetCurrentLanguage is a string.Empty that should be converted to Uri.

**Comment by marisks** [comment]
@alexanddercrb Do you have some custom routing that it uses the `route` parameter as a source URL?

**Comment by alexanddercrb** [comment]
Hello @marisks. Just checked. 
I have a custom redirection with wildcard checked for /some-folder/. Is this what you asked for or I understood it wrong?

**Comment by marisks** [comment]
@alexanddercrb No, I mean why do you have this: "route=/some-folder/folder/page-name/" while in ASP.NET it always sets original URL with "404, 410, or aspxerrorpath="

**Comment by alexanddercrb** [comment]
Ah, sorry. Yes, I have custom routing here.

**Comment by marisks** [comment]
Is this still an issue? Please update to the latest version: https://nuget.episerver.com/package/?id=Geta.404Handler

**Comment by linus-jansson** [comment]
Using the latest
`<package id="Geta.404Handler" version="1.2.1" targetFramework="net472" />`

The issue persists. Using the following config:
```
<httpErrors errorMode="Custom" existingResponse="Replace" xdt:Transform="Insert">
	<remove statusCode="404" />
	<remove statusCode="500" />
	<error statusCode="404" path="/Views/ErrorHandling/ErrorHandler" prefixLanguageFilePath="" responseMode="ExecuteURL" />
	<error statusCode="404" subStatusCode="99" path="/Views/ErrorHandling/OtherErrorPage" prefixLanguageFilePath="" responseMode="ExecuteURL" />
	<error statusCode="500" path="/Views/ErrorHandling/ErrorHandler" prefixLanguageFilePath="" responseMode="ExecuteURL" />
</httpErrors>
```
and appending `[BVNetwork.NotFound.Core.NotFoundPage.NotFoundPage]` to the controllers Index route going to www.example.com/Views/ErrorHandling/ErrorHandler instantly throws the the exception

Anyway to fix this?
