### ISSUE TITLE
RedirectsService AddOrUpdate Not Threadsafe

### ISSUE THREAD

**Issue by MartinH5** [Geta/404handler#160]
Apologizes if this is the wrong place to put this. 

I have created an event to automatically add new redirects, when a page is moved. It works when I move the first page, but an exception is thrown afterwards if I try to move additionally pages. When the following code is called a second time and every time afterwards, it produces an error:

```
public void SaveRedirect(MoveContentEventArgs eventArgs)
        {
            var hostName = SiteDefinition.Current.SiteUrl.ToString();
            hostName = hostName.EndsWith("/") ? hostName.Substring(0, hostName.Length - 1) : hostName;

            var newUrl = hostName + _urlResolver.GetUrl(eventArgs.ContentLink);
            var oldUrl = hostName + _urlResolver.GetUrl(eventArgs.OriginalContentLink);

            _redirectsService.AddOrUpdate(new CustomRedirect(oldUrl.Trim(), newUrl.Trim(), false));
            
            CustomRedirectHandler.ClearCache();
        }
```
The RedirectionService, which holds the SaveRedirect, is Injected into an InitializableModule. Here the method is called from an event. 

```
[InitializableModule]
    [ModuleDependency(typeof(EPiServer.Web.InitializationModule))]
    public class EventsInitialization : IInitializableModule
    {
        private Injected<IContentEvents> _contentEvents;
        private Injected<RedirectionService> _redirectionService;

        public void Initialize(InitializationEngine context)
        {
            _contentEvents.Service.MovedContent += EventsMovingContent;
        }
      
        private void EventsMovingContent(object sender, ContentEventArgs eventArgs)
        {
            if (eventArgs is MoveContentEventArgs args)
            {
                _redirectionService.Service.SaveRedirect(args);
            }
        }
    }
```

The error message, says: 

> Exception thrown: 'System.InvalidOperationException' in EPiServer.Data.dll. An exception of type 'System.InvalidOperationException' occurred in EPiServer.Data.dll but was not handled in user code. Call on database executor not created on current context and on different thread. Possible rooted IDatabaseExecutor, which is not thread safe.

The full stacktrace can found here:

> 2019-08-22 16:33:02,307 [51] ERROR EPiServer.Cms.Shell.UI.Rest.Internal.ContentStore: Failed to move the content "lp" beneath the content "404Page".
> System.InvalidOperationException: Call on database executor not created on current context and on different thread. Possible rooted IDatabaseExecutor, which is not thread safe.
>    at EPiServer.Data.Providers.Internal.SqlDatabaseExecutor.AssertThreadSafe()
>    at EPiServer.Data.Providers.Internal.SqlDatabaseExecutor.Execute[TResult](Func`1 action)
>    at BVNetwork.NotFound.Core.Data.SqlRedirectRepository.ExecuteQuery(Func`1 createCommand)
>    at BVNetwork.NotFound.Core.Data.SqlRedirectRepository.GetByOldUrl(String oldUrl)
>    at BVNetwork.NotFound.Core.CustomRedirects.DefaultRedirectsService.AddOrUpdate(CustomRedirect redirect)
>    at RedirectionHandler.Services.RedirectionService.SaveRedirect(MoveContentEventArgs eventArgs) in \Services\RedirectionService.cs:line 36
>    at RedirectionHandler.Business.EventsInitialization.EventsMovingContent(Object sender, ContentEventArgs eventArgs) in \Business\EventsInitialization.cs:line 34
>    at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
>    at EPiServer.Core.Internal.DefaultContentEvents.RaiseContentEvent(String key, ContentEventArgs eventArgs)
>    at EPiServer.Core.Internal.DefaultContentRepository.Move(ContentReference contentLink, ContentReference destinationLink, AccessLevel requiredSourceAccess, AccessLevel requiredDestinationAccess)
>    at EPiServer.IContentRepositoryExtension.Move(IContentRepository contentRepository, ContentReference contentLink, ContentReference destination)
>    at EPiServer.Cms.Shell.Service.Internal.ContentService.Move(IContent content, ContentReference destination)
>    at EPiServer.Cms.Shell.UI.Rest.ContentChangeManager.Move(IContent source, IContent destination, Boolean createAsLocalAsset)
>    at EPiServer.Cms.Shell.UI.Rest.Internal.ContentStore.MoveContent(IContent source, IContent destination, Boolean createAsLocalAsset, ActionResponse`1 response)
> System.InvalidOperationException: Call on database executor not created on current context and on different thread. Possible rooted IDatabaseExecutor, which is not thread safe.
>    at EPiServer.Data.Providers.Internal.SqlDatabaseExecutor.AssertThreadSafe()
>    at EPiServer.Data.Providers.Internal.SqlDatabaseExecutor.Execute[TResult](Func`1 action)
>    at BVNetwork.NotFound.Core.Data.SqlRedirectRepository.ExecuteQuery(Func`1 createCommand)
>    at BVNetwork.NotFound.Core.Data.SqlRedirectRepository.GetByOldUrl(String oldUrl)
>    at BVNetwork.NotFound.Core.CustomRedirects.DefaultRedirectsService.AddOrUpdate(CustomRedirect redirect)
>    at RedirectionHandler.Services.RedirectionService.SaveRedirect(MoveContentEventArgs eventArgs) in RedirectionHandler\Services\RedirectionService.cs:line 36
>    at RedirectionHandler.Business.EventsInitialization.EventsMovingContent(Object sender, ContentEventArgs eventArgs) in \RedirectionHandler\Business\EventsInitialization.cs:line 34
>    at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
>    at EPiServer.Core.Internal.DefaultContentEvents.RaiseContentEvent(String key, ContentEventArgs eventArgs)
>    at EPiServer.Core.Internal.DefaultContentRepository.Move(ContentReference contentLink, ContentReference destinationLink, AccessLevel requiredSourceAccess, AccessLevel requiredDestinationAccess)
>    at EPiServer.IContentRepositoryExtension.Move(IContentRepository contentRepository, ContentReference contentLink, ContentReference destination)
>    at EPiServer.Cms.Shell.Service.Internal.ContentService.Move(IContent content, ContentReference destination)
>    at EPiServer.Cms.Shell.UI.Rest.ContentChangeManager.Move(IContent source, IContent destination, Boolean createAsLocalAsset)
>    at EPiServer.Cms.Shell.UI.Rest.Internal.ContentStore.MoveContent(IContent source, IContent destination, Boolean createAsLocalAsset, ActionResponse`1 response)

**Comment by MartinH5** [comment]
Sorry for the messy edits, haven't dealt much with Github's issue system.

**Comment by MartinH5** [comment]
Issue resolved. I had the IRedirectsService Injected<> into my InitializableModule. It was resolved by using the ServiceLocator to access the service, rather than injecting it into my module:

 ` ServiceLocator.Current.GetInstance<IRedirectsService >().SaveRedirect(args); `
