### ISSUE TITLE
BVNetwork.NotFound.Core.Data.DataAccessBaseEx : An error occurred while logging a 404 handler error.

### ISSUE THREAD

**Issue by sushmitasen11** [Geta/404handler#192]
BVNetwork.NotFound.Core.Data.DataAccessBaseEx : An error occurred while logging a 404 handler error.
System.Data.SqlClient.SqlException (0x80131904): String or binary data would be truncated.
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at BVNetwork.NotFound.Core.Data.DataAccessBaseEx.<>c__DisplayClass15_0.<LogRequestToDb>b__0()
ClientConnectionId:00e0d577-838a-49ea-8cfd-b21ee69937d4
Error Number:8152,State:30,Class:16
ClientConnectionId before routing:7c4a665b-9608-497e-a7a2-d100f0b58fff
Routing Destination:b78e4e6ba90c.HS3.tr3144.northeurope1-a.worker.database.windows.net,11011

**Comment by marisks** [comment]
@sushmitasen11 There is a fix for the size of parameters: #189 
After the release, it might fix this.

Do you know what URL it tried to log? The max length is 2000 chars.

**Comment by sushmitasen11** [comment]
i have 11.3.0 version installed still i get this issue ? In which version is this bug fixed ?

I am not having specific url to check this.

**Comment by marisks** [comment]
It is not yet released.

**Comment by sushmitasen11** [comment]
Ok thanks @marisks

**Comment by marisks** [comment]
The fix released in Geta.404Handler - 1.2.0
