### ISSUE TITLE
Logging error?

### ISSUE THREAD

**Issue by andemt** [Geta/404handler#206]
I get this error:
```
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at EPiServer.Logging.Internal.LoggerMessageFormatter.<>c.<.cctor>b__7_1(Tuple`2 s, Exception ex)
   at EPiServer.Logging.Log4Net.Log4NetLoggerFactory.Log4NetLogger.Log[TState,TException](Level level, TState state, TException exception, Func`3 messageFormatter, Type boundaryType)
   at EPiServer.Logging.LogManager.LazyLogger.Log[TState,TException](Level level, TState state, TException exception, Func`3 messageFormatter, Type boundaryType)
   at EPiServer.Logging.LoggerExtensions.Log(ILogger logger, Level level, String messageFormat, Object[] args)
   at BVNetwork.NotFound.Controllers.NotFoundRedirectController.SaveRedirect(String oldUrl, String newUrl, String skipWildCardAppend, RedirectType redirectType)
   at BVNetwork.NotFound.Controllers.NotFoundRedirectController.Save(String oldUrl, String newUrl, String skipWildCardAppend, RedirectType redirectType, Nullable`1 pageNumber, Nullable`1 pageSize)
```

https://github.com/Geta/404handler/blob/master/src/Geta.404Handler/Controllers/NotFoundRedirectController.cs

`Logger.Debug("Adding redirect: '{0}' -> '{1}' ({3})", oldUrl, newUrl, redirectType);`

Problem if oldUrl, newUrl or redirectType is null/empty?

**Comment by andemt** [comment]
Ey, you have a "3" instead of "2"

`Logger.Debug("Adding redirect: '{0}' -> '{1}' ({2})", oldUrl, newUrl, redirectType);`

**Comment by marisks** [comment]
Fixed in https://github.com/Geta/404handler/pull/208
