### ISSUE TITLE
404 handler still logs in Episerver default EPiServerErrors.log

### ISSUE THREAD

**Issue by akfo** [Geta/404handler#35]
We have setup the 404handler in our solution. Unfortunately we are seeing a lot of messages like this in our EPiServerErrors.log file:

2017-03-24 07:25:00,806 [951] ERROR EPiServer.Global: 1.2.5 Unhandled exception in ASP.NET
2017-03-24 07:25:04,821 [2118] ERROR EPiServer.Global: 1.2.5 Unhandled exception in ASP.NET
2017-03-24 07:25:09,884 [2435] ERROR EPiServer.Global: 1.2.5 Unhandled exception in ASP.NET
2017-03-24 07:25:30,915 [2161] ERROR EPiServer.Global: 1.2.5 Unhandled exception in ASP.NET
2017-03-24 07:25:46,665 [2161] ERROR EPiServer.Global: 1.2.5 Unhandled exception in ASP.NET
2017-03-24 07:26:34,103 [2118] ERROR EPiServer.Global: 1.2.5 Unhandled exception in ASP.NET
2017-03-24 07:26:34,462 [4036] ERROR EPiServer.Global: 1.2.5 Unhandled exception in ASP.NET
2017-03-24 07:26:38,134 [3965] ERROR EPiServer.Global: 1.2.5 Unhandled exception in ASP.NET

Our debugging have identified that these log lines corresponds to 404 requests being caught by the 404 handler but still being logged by Episerver. We have tried to register our own handler for UnhandledExceptions in Global.asax, and can get an output like this:

2017-03-24 07:25:04,821 [2118] ERROR UnhandledExceptions: Unhandled Exception
System.Web.HttpException (0x80004005): The controller for path '/favicon.ico' was not found or does not implement IController.
   at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
   at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
   at System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory)
   at System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

In the Episerver documentation there is a listing of the Episerver.Global. It is probably a bit old, but I think the UnhandledException handling is still close to how it is today: http://world.episerver.com/documentation/class-library/?documentId=cms/7/e9e09ee4-16f6-ec1e-fc40-180b192c7f05

See this the method below.

Somehow the exception handled by the 404 handler still triggers the Global_Error eventlistener, but the Server.GetLastError() method returns null. This means that the logging line only logs the method, and since e=null, no exception is logged.

Question: Is this something you can handle in the 404handler, or do we need to involve Episerver to get them to fix their event handling?

private void Global_Error(object sender, EventArgs evt)
        {
            if (HttpContext.Current == null)
            {
                return;
            }

            Exception e;
            try
            {
                //Get the previous exception
                e = Server.GetLastError();
            }
            catch
            {
                return;
            }

            if (e is UnauthorizedAccessException)
            {
                HandleAccessDenied();
            }

            _log.Error("1.2.5 Unhandled exception in ASP.NET", e);

            // Try to get the InconsistentDataException instance that caused the current exception
            InconsistentDataException inconsistent = e.InnerException as InconsistentDataException;
            if (inconsistent != null)
            {
                // The rare case where a delayed long string load fails to retrieve the correct data. Clear cache for
                // the relevant page to avoid that this error happens again for the same page.
                CacheManager.Remove("EPPageData:" + new PageReference(inconsistent.PageLink.ID, EPiServer.Configuration.Settings.Instance.Parent.SiteId).ToString());
            }

            if (!EnableGlobalErrorHandling)
            {
                return;
            }

            if (HttpContext.Current.Items.Contains("EPHandledUnhandledException"))
            {
                return;
            }

            try
            {
                // Clears the previous exception
                Server.ClearError();
                HttpContext.Current.Items.Add("EPHandledUnhandledException", true);
                //Clears all content output from the buffer stream
                Response.Clear();
                //Renders an error message to the user based on the exception
                ExceptionManager.RenderHttpRuntimeError(e);
                Response.End();
            }
            catch 
            {
            }
        }

Thank you for your help.

Regards
Anders

**Comment by marisks** [comment]
Do you still have this issue?
This was a bug in Episerver which is fixed in the latest versions.
