### ISSUE TITLE
ERROR BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization: Error on 404 handling.

### ISSUE THREAD

**Issue by oyjonass** [Geta/404handler#86]
Installed latest (11.1.3) and get a lot of errors in my log

2018-03-12 23:59:24,727 [27] ERROR BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization: Error on 404 handling.
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponseWrapper.RedirectPermanent(String url)
   at BVNetwork.NotFound.Core.Web.HttpContextBaseExtensions.RedirectPermanent(HttpContextBase context, String url)
   at BVNetwork.NotFound.Core.RequestHandler.Handle(HttpContextBase context)
   at BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization.OnEndRequest(Object sender, EventArgs eventArgs)
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort(Object stateInfo)
   at System.Web.HttpResponse.AbortCurrentThread()
   at System.Web.HttpResponse.Redirect(String url, Boolean endResponse, Boolean permanent)
   at System.Web.HttpResponseWrapper.RedirectPermanent(String url)
   at BVNetwork.NotFound.Core.Web.HttpContextBaseExtensions.RedirectPermanent(HttpContextBase context, String url)
   at BVNetwork.NotFound.Core.RequestHandler.Handle(HttpContextBase context)
   at BVNetwork.NotFound.Core.Initialization.Custom404HandlerInitialization.OnEndRequest(Object sender, EventArgs eventArgs)

Any clue?

**Comment by marisks** [comment]
I have added exception logging. So now all exceptions are logged.
Thread abort exception is always thrown when a Response.Redirect or Response.RedirectPermanent is called.
Before exception logging, those errors were just not visible. I will check what can be done to fix this.

**Comment by davidelias0** [comment]
Thanks, we are receiving the exact same error.  On a load test we ran into the error 1500 times in a 1hr load test.  Whould be nice to either not have it logged or if it is an issue fixed.

**Comment by marisks** [comment]
This is fixed in: https://github.com/Geta/404handler/commit/87ac607607c01e6853469bf3d8d7a50b690851bb

But unfortunately nuget.episerver.com doesn't work now and I am not able to upload new packages.
